# Juego de crear una historia loca.



print("¡Bienvenido/a! Este juego trata de crear la historia más loca que puedas")
print("poniendo las palabras que se te pidan para posteriormente crear una historia.")
print("¡Diviértete!\n")
input("Presiona 'Enter' para continuar")
pte_del_cuerpo_plu = input("Escribe una parte del cuerpo humano plurar: ").lower()
adj_mas_plu = input("Escribe un adjetivo masculino plural: ").lower()
adj_mas_sin = input("Escribe un adjetivo masculino singular: ").lower()
adj_mas_sin2 = input("Escribe un adjetivo masculino singular: ").lower()
lugar = input("Escribe un lugar: ").capitalize()
animal = input("Escribe un animal singular: ").lower()
pte_del_cuerpo_sin = input("Escribe una parte del cuerpo humano singular: ").lower()
adj_sin3 = input("Escribe un adjetivo singular: ").lower()
adj_fem_plu = input("Escribe un adjetivo femenino plural: ").lower()
adv = input("Escribe un adverbio: ").lower()
interjeccion = input("Escribe una interjección singular: ").upper()
adj_fem_plu2 = input("Escribe un adjetivo femenino plural: ").lower()
nombre_propio = input("Escribe un nombre propio: ").capitalize()
nombre = input("Escribe un nombre singular: ").lower()

print(f"\n\nAntiguamente, el ser humano caminaba a cuatro {pte_del_cuerpo_plu},")
print(f"se expresaba mediante gruñidos {adj_mas_plu} y no sabía encender")
print(f"un {adj_mas_sin} fuego. Esta es la historia del día en el que la humanidad")
print(f"cambió para siempre (traducida del {adj_mas_sin2} idioma de las cavernas):\n")
print("Hombre de las cavernas 1: En esta cueva hace más frío que en (el/la)")
print(f"{lugar}. Incluso con la piel del/de la {animal} más caliente no")
print(f"consigo que mi {pte_del_cuerpo_sin} deje de tiritar.")
print("Hombre de las cavernas 2: Si al menos pudiésemos encontrar una")
print(f"manera de que el frío fuera más {adj_sin3}.\n")
print("Hombre de las cavernas 1: Estoy aburrido. Creo que voy a jugar un")
print(f"rato con estas ramas {adj_fem_plu}.")
print(f"Hombre de las cavernas 2: ¿Por qué no te las frotas {adv} a ver")
print("qué pasa?\n")
print(f"Hombre de las cavernas 1: ¡{interjeccion}! ¡Está saliendo humo de")
print(f"las {adj_fem_plu2} ramas!")
print("Hombre de las cavernas 2: ¡Ay! ¡Está caliente! ¡Por el amor de")
print(f"{nombre_propio}, hemos conseguido calor!\n")
print("Hombre de las cavernas 1: A partir de ahora, llamaremos 'fuego' a esta")
print(f"{nombre} mágica.")
